# Imagen ligera de Python
FROM python:3.12-slim

WORKDIR /app

# Instalamos dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos todo el código fuente
COPY . .

EXPOSE 8501

# Comando de arranque para Streamlit
CMD ["streamlit", "run", "src/app_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]